{{- range $index, $singleton := .Values.singletons }}
{{- $singleton := merge $.Values.global $singleton }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "s-%s" (include "tensorflow-serving.sanitizeModelName" $singleton.modelId) }}
  namespace: {{ include "tensorflow-serving.namespace" $ }}
  annotations:
    {{- toYaml $.Values.global.service.annotations | nindent 4 }}
  labels:
    app.kubernetes.io/name: tensorflow-serving
    app.kubernetes.io/instance: {{ include "tensorflow-serving.name" $ }}
    modelId: {{ $singleton.modelId }}
spec:
  type: {{ $singleton.service.type | default $.Values.global.service.type }}
  ports:
  - port: {{ $.Values.global.service.port }}
    targetPort: {{ $singleton.service.targetPort | default $.Values.global.service.targetPort }}
  selector:
    app.kubernetes.io/name: tensorflow-serving
    modelId: {{ $singleton.modelId }}
{{- end }}

{{- range $index, $group := .Values.groups }}
{{- $group := merge $.Values.global $group }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "s-%s" (include "tensorflow-serving.sanitizeModelName" $group.groupId) }}
  namespace: {{ include "tensorflow-serving.namespace" $ }}
  annotations:
    {{- toYaml $.Values.global.service.annotations | nindent 4 }}
  labels:
    app.kubernetes.io/name: tensorflow-serving
    app.kubernetes.io/instance: {{ include "tensorflow-serving.name" $ }}
    groupId: {{ $group.groupId }}
spec:
  type: {{ $group.service.type }}
  ports:
  - port: {{ $.Values.global.service.port }}
    targetPort: {{ $group.service.targetPort }}
  selector:
    app.kubernetes.io/name: tensorflow-serving
    groupId: {{ $group.groupId }}
{{- end }}