{{- range $index, $dep := .Values.deployments }}
{{ $gc := deepCopy $.Values.global }}
{{- $dep := mergeOverwrite $gc $dep }}
{{- if not $dep.knative.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "s-%s" (include "tensorflow-serving.sanitizeModelName" $dep.name) }}
  namespace: {{ include "tensorflow-serving.namespace" $ }}
  annotations:
    {{- toYaml $.Values.global.service.annotations | nindent 4 }}
  labels:
    app.kubernetes.io/name: tensorflow-serving
    app.kubernetes.io/instance: {{ include "tensorflow-serving.name" $ }}
    deploymentName: {{ $dep.name }}
spec:
  type: {{ $dep.service.type | default $.Values.global.service.type }}
  ports:
  - port: {{ $dep.service.port | default $.Values.global.service.port | default 80 }}
    targetPort: {{ $dep.service.targetPort | default $.Values.global.service.targetPort }}
  selector:
    app.kubernetes.io/name: tensorflow-serving
    deploymentName: {{ $dep.name }}
{{- end }}
{{- end }}
